language: go
sudo: false

go:
  # logrus includes golang.org/x/sys/unix/affinity_linux.go which requires go 1.9
  - 1.9
  - 1.x
  - master

before_install:
  - go get golang.org/x/tools/cmd/goimports

script: make all && go tool vet . && goimports -l . | grep -v assets | wc -l | grep '0$' && go fix
